### ISSUE TITLE
rep Error

### ISSUE THREAD

**Issue by mdupilka** [dankelley/windbarb#1]
I used the new code 2cc7537. I still get the same error: Error in rep(1, fi[["pennant"]]) : invalid 'times' argument. I printed the value and it is NA. As I mentioned, I use the same arguments for mapDirectionFieldBarbs() as with mapDirectionField(). Lon, lat are vectors and u, v are matrices.

**Comment by mdupilka** [comment]
Does the barb plotting handle NA values. There are some grid values I set NA so they will not be plotted. These are just not plotted with the mapDirectionField(), which is what I want.

**Comment by mdupilka** [comment]
Instead of setting the values to NA I set them to 0. The same error continues.

**Comment by dankelley** [comment]
@mdupilka -- please move your comment about NA to a new issue.  Otherwise we run the risk of multiple topics in one issue, which is confusing.  One issue per topic, please.

NOTE to @richardsc -- we have moved discussion of barbs over here, because it's convenient for sharing rapidly-evolving code.  Basically, a person can test by doing
```
git pull ; make
```
in the directory, for the standard tests, or maybe
```
git pull ; Rscript myscript.R
```
for a user's own tests.  That's fast even if you type it, but of course users will likely type control-R to get back the previous, or `!g` to repeat the command.  And, for my part, pushing a new version is similar: I type `!g`.

**Comment by mdupilka** [comment]
Ok. I thought this issue was about the windbarb code which is not working.

**Comment by mdupilka** [comment]
I got the windbarbs working. They look very good. However, I found out it cannot seem to handle NA data values. If I replace those with zero is works. But for my purposes that is not a good solution. If there is missing NA data I do not want it to plot. This is how the mapDirectionField() works.

**Comment by mdupilka** [comment]
Another issue is that the wind directions do not look to be correct in many cases. As a test, they should line up with the wind arrows using the mapDirectionField(), which produces a good direction.

**Comment by richardsc** [comment]
Hi max -- can you provide a small reprex (reproducible example) with code showing a case where the barbs don't line up?

**Comment by mdupilka** [comment]
The code I have is a bit complicated, but I will see if I can boil it down to something simple.

**Comment by mdupilka** [comment]
I will send you an email since Github does not let me upload an RData file that I used.

**Comment by dankelley** [comment]
Solved
