### ISSUE TITLE
lcc: Invalid longitude

### ISSUE THREAD

**Issue by mdupilka** [dankelley/windbarb#7]
I get many of these messages "lcc: Invalid longitude". I recall this happened when drawing the arrows and it was something to do with not being able to draw past the border I think. You cleaned  it up. This does not affect the plotting, just gives a lot of messages.

**Comment by dankelley** [comment]
I don't think we can do anything about that.  It seems to be a low-level message from the C (or C++ or fortran) code that is used deep down in R, for map projections.

This compiled code is not supposed to print directly (using `printf()`, say), but is instead supposed to use something called `Rprintf()`, because the latter permits the user to silence output, or capture it to a string with the `capture.output()` function.  I tried capturing the output and it did not work.  Therefore, I think the underlying code is using `printf()` or similar.

Usually these things go away over time, as developers notice such messages in their own work, and go into the code to make the change that is recommended.

@mdupilka if you think this issue has been addressed by the present comment, please close it.  (That's the convention we use in the oce community.)
